// <auto-generated />
namespace WEBAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class sf2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sf2));
        
        string IMigrationMetadata.Id
        {
            get { return "202011010613566_sf--2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
